[build]
builder = "NIXPACKS"
watchPatterns = ["src/**"]
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
numReplicas = 2 