export { Header } from './Header';
export { Footer } from './Footer';
export { HeroSection } from './HeroSection';
export { Platform } from './Platform';
export { FAQ } from './FAQ';
export { PaymentSol } from './PaymentSol';
export { Immersion } from './Immersion';
export { ChatPerformance } from './ChatPerformance';
export { ChatPerformanceV2 } from './ChatPerformanceV2';
export { default as Chatbot } from './Chatbot';
export { default as ExampleChatbot } from './ExampleChatbot';
export { PlanCard } from './PlanCard';
export { MarqueeComponent } from './MarqueeComponent';
export { default as DashboardSection } from './DashboardSection';
export { CalendlyModal } from './CalendlyModal'; 